config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port:3000
  resources :shifts
  resources :employees, :managers
  resources :schedules, only: [:show]
  resources :organizations
  resources :departments

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'console' => 'console#index'

  get 'signup' => 'employees#new_signup', as: 'new_signup'
  post '/employees' => 'employees#signup', as: 'signup'

  get 'login' => 'sessions#login', as: 'login'
  post 'login' => 'sessions#create'
  get "/auth/:provider/callback" => 'sessions#oauth'
  delete 'logout' => 'sessions#destroy'

  get '/calendar' => 'calendars#index'

  get 'organizations/join/:id' => 'organizations#join', as: 'join_organization'
  get '/switch/:id' => 'departments#switch', as: 'switch_department'

  get 'verification/:token' => 'employees#verify', as: 'verify_email'

  get 'email/schedule/:id' => 'schedules#email_schedule', as: 'email_schedule'
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :schedule
  has_one :employee, through: :schedule
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  load_and_authorize_resource

  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    department = current_employee.department
    @shifts = department.shifts

    respond_to do |format|
      format.html { render :index }
      format.json { render json: {'success': 1, 'result': serialized_shifts} }
    end
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
    @schedules = Schedule.where(department_id: current_employee.department_id)
  end

  # GET /shifts/1/edit
  def edit
    @schedules = Schedule.where(department_id: current_employee.department_id)
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:shift_description, :start_time, :end_time, :schedule_id)
    end

    def serialized_shifts
      ActiveModel::ArraySerializer.new(@shifts).as_json
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_for(@shift, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @shift.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h4>

      <ul>
      <% @shift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :shift_description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :shift_description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :start_time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :end_time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :schedule_id, 'Assigned to', class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select(:schedule_id, @schedules, :id, :employee_name) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<div class="page-header">
  <%= link_to shifts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @shift, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing shift</h1>
</div>

<%= render 'form' %>

app/views/shifts/index.html.erb
<div class="page-header">
  <%= link_to console_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to new_shift_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Shift
  <% end %>
  <h1>Listing shifts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Shift description</th>
            <th>Start time</th>
            <th>End time</th>
            <th>Assigned to</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @shifts) do |shift| %>
            <td><%= shift.shift_description %></td>
            <td><%= shift.start_time.strftime('%a, %b %d - %I:%M %p') %></td>
            <td><%= shift.end_time.strftime('%a, %b %d - %I:%M %p') %></td>
            <td><%= "#{shift.schedule.employee.first_name} #{shift.schedule.employee.last_name}" %></td>
            <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shifts/new.html.erb
<div class="page-header">
  <%= link_to shifts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New shift</h1>
</div>

<%= render 'form' %>

app/views/shifts/show.html.erb
<div class="page-header">
  <%= link_to shifts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_shift_path(@shift), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show shift</h1>
</div>

<dl class="dl-horizontal">
  <dt>Shift description:</dt>
  <dd><%= @shift.shift_description %></dd>

  <dt>Start time:</dt>
  <dd><%= @shift.start_time.strftime('%a, %b %d - %I:%M %p') %></dd>

  <dt>End time:</dt>
  <dd><%= @shift.end_time.strftime('%a, %b %d - %I:%M %p') %></dd>

  <dt>Assigned to:</dt>
  <dd><%= "#{@shift.schedule.employee.first_name} #{@shift.schedule.employee.last_name}" %></dd>

</dl>