config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port:3000
  resources :shifts
  resources :employees, :managers
  resources :schedules, only: [:show]
  resources :organizations
  resources :departments

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'console' => 'console#index'

  get 'signup' => 'employees#new_signup', as: 'new_signup'
  post '/employees' => 'employees#signup', as: 'signup'

  get 'login' => 'sessions#login', as: 'login'
  post 'login' => 'sessions#create'
  get "/auth/:provider/callback" => 'sessions#oauth'
  delete 'logout' => 'sessions#destroy'

  get '/calendar' => 'calendars#index'

  get 'organizations/join/:id' => 'organizations#join', as: 'join_organization'
  get '/switch/:id' => 'departments#switch', as: 'switch_department'

  get 'verification/:token' => 'employees#verify', as: 'verify_email'

  get 'email/schedule/:id' => 'schedules#email_schedule', as: 'email_schedule'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :departments
  has_many :employees
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  load_and_authorize_resource

  before_action :set_organization, only: [:show, :join]
  def new
    @organization = Organization.new
  end
  
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        current_employee.type = 'Manager'
        current_employee.organization_id = @organization.id
        current_employee.save
        format.html { redirect_to departments_path, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @organizations = Organization.all
  end

  def join
    current_employee.organization_id = @organization.id
    current_employee.save
    redirect_to departments_path
  end


  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name)
  end

end

app/views/organizations/_form.html.erb
<%= form_for(@organization, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @organization.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h4>

      <ul>
        <% @organization.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/organizations/_helper_box.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Welcome to DaVinci Shift Scheduler!
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p>
          Thank you for choosing to use DaVinci Shift Scheduler! There are many apps to choose
          from and we appriciate you using ours!
        </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Getting started
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <p>
          To get started either create an organization or join an existing one.
          This allows you to have a place to store all your calendars and schedules.
          By creating a new organization you will have admin permissions for that organization.
        </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Tips
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <p>
          Organizations will allow you create departments within them. This helps make it easy to manage your schedules
        </p>

        <p>
          Each department you create can have its own individual group of employees. You can have multiple departments
          and easily switch between them to work on different schedules.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/organizations/index.html.erb
<%= render 'organizations/helper_box' %>



<div>
  <div class="page-header">
    <%= link_to new_organization_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Organization
    <% end %>
    <h1>Listing Organizations</h1>
  </div>

  <div class="table-responsive">
    <table id="organization_table" class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <%= content_tag_for(:tr, @organizations) do |organization| %>
        <td><%= organization.name %></td>
        <td><%= link_to 'Join', join_organization_path(organization) %></td>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="page-header">
  <%= link_to organizations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Organization</h1>
</div>

<%= render 'form' %>

app/views/organizations/show.html.erb
<div class="page-header">
  <%= link_to organizations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to root_path(), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Departments</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @departments.name %></dd>

</dl>