config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port:3000
  resources :shifts
  resources :employees, :managers
  resources :schedules, only: [:show]
  resources :organizations
  resources :departments

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'console' => 'console#index'

  get 'signup' => 'employees#new_signup', as: 'new_signup'
  post '/employees' => 'employees#signup', as: 'signup'

  get 'login' => 'sessions#login', as: 'login'
  post 'login' => 'sessions#create'
  get "/auth/:provider/callback" => 'sessions#oauth'
  delete 'logout' => 'sessions#destroy'

  get '/calendar' => 'calendars#index'

  get 'organizations/join/:id' => 'organizations#join', as: 'join_organization'
  get '/switch/:id' => 'departments#switch', as: 'switch_department'

  get 'verification/:token' => 'employees#verify', as: 'verify_email'

  get 'email/schedule/:id' => 'schedules#email_schedule', as: 'email_schedule'
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  def index
    if !current_employee
      redirect_to root_path
    else
      @departments = Department.where(organization_id: current_employee.organization_id)
      @employees = Employee.where(department_id: current_employee.department_id)
    end
  end
end

app/views/console/_help_button.html.erb
<button class="btn btn-default" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  help
</button>
<div class="collapse" id="collapseExample">
  <div class="well">
    <button class='btn btn-primary glyphicon glyphicon-ok' data-toggle="tooltip" data-placement="bottom" title="Current working departments"></button>
    <button class='btn btn-primary glyphicon glyphicon-transfer' data-toggle="tooltip" data-placement="bottom" title="Switch departments"></button>
    <button class='btn btn-primary glyphicon glyphicon-pencil' data-toggle="tooltip" data-placement="bottom" title="Edit"></button>
    <button class='btn btn-primary glyphicon glyphicon-eye-open' data-toggle="tooltip" data-placement="bottom" title="Show"></button>
    <button class='btn btn-primary glyphicon glyphicon-calendar' data-toggle="tooltip" data-placement="bottom" title="View schedule"></button>
    <button class='btn btn-primary glyphicon glyphicon-envelope' data-toggle="tooltip" data-placement="bottom" title="Email schedule"></button>
    <button class='btn btn-danger glyphicon glyphicon-trash' data-toggle="tooltip" data-placement="bottom" title="Remove employee"></button>
  </div>
</div>

app/views/console/_toolbar.html.erb
<div class="container">
  <div class="">
    <%= link_to new_department_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Department
    <% end %>

    <%= link_to new_employee_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Employee
    <% end %>

    <%= link_to new_shift_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Shift
    <% end %>


    <%= render 'console/help_button' %>
  </div>
</div>

app/views/console/index.html.erb
<% if can? :manage, :all %>
  <%= render 'console/toolbar' %>
<% end %>

<!--Department Table-->
<div class="col-md-5 console-panel">
  <div class="page-header">
    <h1><%= link_to 'Departments', departments_path %></h1>
  </div>

  <div class="table-responsive" style="height: 210px" overflow="scroll">
    <table id="department_table" class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <% if can? :manage, :all %>
          <th></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <%= content_tag_for(:tr, @departments) do |department| %>
        <td><%= department.name %></td>
        <% if department == current_department %>
          <td style="width: 10%"><%= link_to '', switch_department_path(department), class: 'btn btn-primary glyphicon glyphicon-ok' %></td>
        <% else %>
          <td style="width: 10%"><%= link_to '', switch_department_path(department), class: 'btn btn-primary glyphicon glyphicon-transfer' %></td>
        <% end %>
        <% if can? :manage, :all %>
          <td style="width: 10%"><%= link_to '', edit_department_path(department), class: 'btn btn-primary glyphicon glyphicon-pencil' %></td>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <hr>
</div>


<!--Employee Table-->

<div class="col-md-7 console-panel">

  <div class="page-header">
    <h1><%= link_to 'Employees', employees_path %></h1>
  </div>

  <div class="table-responsive" style="height: 210px" overflow="scroll">
    <table id="employee_table" class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
        <% if can? :manage, :all %>
          <th></th>
          <th></th>
          <th></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <%= content_tag_for(:tr, @employees) do |employee| %>
        <td><%= employee.first_name + ' ' + employee.last_name %></td>
        <td style="width: 10%"><%= link_to '', employee_path(employee), class: 'btn btn-primary glyphicon glyphicon-eye-open' %></td>
        <td style="width: 10%"><%= link_to '', schedule_path(employee), class: 'btn btn-primary glyphicon glyphicon-calendar' %></td>
        <% if can? :manage, :all %>
          <td style="width: 10%"><%= link_to '', email_schedule_path(employee), class: 'btn btn-primary glyphicon glyphicon-envelope' %></td>
          <td style="width: 10%"><%= link_to '', edit_employee_path(employee), class: 'btn btn-primary glyphicon glyphicon-pencil' %></td>
          <td style="width: 10%"><%= link_to '', employee, class: 'btn btn-danger glyphicon glyphicon-trash', method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <hr>
</div>
</div>


<div class="container">
  <div class="page-header">
    <h1><%= link_to 'Calendar', calendar_path %></h1>
  </div>
  <%= render 'calendars/calendar' %>
</div>

<div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>