config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port:3000
  resources :shifts
  resources :employees, :managers
  resources :schedules, only: [:show]
  resources :organizations
  resources :departments

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'console' => 'console#index'

  get 'signup' => 'employees#new_signup', as: 'new_signup'
  post '/employees' => 'employees#signup', as: 'signup'

  get 'login' => 'sessions#login', as: 'login'
  post 'login' => 'sessions#create'
  get "/auth/:provider/callback" => 'sessions#oauth'
  delete 'logout' => 'sessions#destroy'

  get '/calendar' => 'calendars#index'

  get 'organizations/join/:id' => 'organizations#join', as: 'join_organization'
  get '/switch/:id' => 'departments#switch', as: 'switch_department'

  get 'verification/:token' => 'employees#verify', as: 'verify_email'

  get 'email/schedule/:id' => 'schedules#email_schedule', as: 'email_schedule'
end

app/views/layouts/_authentication.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <% if current_employee %>
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_employee.email %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li><%= link_to 'Settings', "/employees/#{current_employee.id}/edit" %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Signup', new_employee_path %></li>
      <li><%= link_to 'Login', login_path %></li>
    <% end %>
    </ul>
  </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_employee %>
        <%= link_to "Shift Scheduler", console_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "Shift Scheduler", root_path, class: "navbar-brand" %>
      <% end %>

    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <% if current_employee.present? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Schedule
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Calendar', calendar_path %></li>
              <li><%= link_to 'My Schedule', schedule_path(current_employee) %></li>
            </ul>
          </li>
        <% end %>
        <% if can? :manage, :all %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Shifts
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Shifts", shifts_path %></li>
              <li><%= link_to "Add Shift", new_shift_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Employees
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Employees", employees_path %></li>
              <li><%= link_to "Add Employee", new_employee_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Departments
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% current_employee.organization.departments.each do |department| %>
                <li><%= link_to department.name, switch_department_path(department) %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Add Department", new_department_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <%= render 'layouts/authentication' %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <div style="position: fixed !important; margin-left: 30% !important; margin-right: 30% !important; margin-top: 4px !important;">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
        <script>
          setTimeout("$('.alert').fadeOut('slow')", 3000)
        </script>
      <% end %>
    <% end %>
  </div>

  <% if current_employee && current_employee.department.present? %>
    <div class="well">
      Current Department: <%= current_employee.department.name %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>